name: Deploy vitepress site to GitHub Pages

on:
  push:
    branches:
      - main  # or 'master' â€” use your default branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          persist-credentials: false  # needed for deploy token auth
          ruby-version: '3.0'  # specify the Ruby version you're using
          bundler-cache: true   # enable caching for gems to speed up deployments
          
      # Install dependencies from Gemfile
      - name: Install dependencies
        run: |
          gem install bundler
          bundle install  # this will install Faraday v2.0+ and any other gems listed

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Build vitepress site
        run: npm run docs:build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .vitepress/dist
          cname: marketplace-doc1.webkul.com
